//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coconuts
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CoconutsEntities : DbContext
    {
        public CoconutsEntities()
            : base("name=CoconutsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PRENDAS> PRENDAS { get; set; }
        public virtual DbSet<PUBLICACIONES> PUBLICACIONES { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
    
        public virtual int sp_EliminarPublicacion(Nullable<int> idpublicaciones, string descripcion, Nullable<int> idusuario)
        {
            var idpublicacionesParameter = idpublicaciones.HasValue ?
                new ObjectParameter("idpublicaciones", idpublicaciones) :
                new ObjectParameter("idpublicaciones", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var idusuarioParameter = idusuario.HasValue ?
                new ObjectParameter("idusuario", idusuario) :
                new ObjectParameter("idusuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EliminarPublicacion", idpublicacionesParameter, descripcionParameter, idusuarioParameter);
        }
    
        public virtual int sp_ModPrenda(Nullable<int> idprendas, string descripcion, Nullable<decimal> precio, Nullable<int> idpublicaciones, string modelo)
        {
            var idprendasParameter = idprendas.HasValue ?
                new ObjectParameter("idprendas", idprendas) :
                new ObjectParameter("idprendas", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var precioParameter = precio.HasValue ?
                new ObjectParameter("precio", precio) :
                new ObjectParameter("precio", typeof(decimal));
    
            var idpublicacionesParameter = idpublicaciones.HasValue ?
                new ObjectParameter("idpublicaciones", idpublicaciones) :
                new ObjectParameter("idpublicaciones", typeof(int));
    
            var modeloParameter = modelo != null ?
                new ObjectParameter("modelo", modelo) :
                new ObjectParameter("modelo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ModPrenda", idprendasParameter, descripcionParameter, precioParameter, idpublicacionesParameter, modeloParameter);
        }
    
        public virtual int sp_NuevoUsuario(string nombre, string apellido, string sexo, Nullable<System.DateTime> fecha_alta, Nullable<int> idusuario)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("apellido", apellido) :
                new ObjectParameter("apellido", typeof(string));
    
            var sexoParameter = sexo != null ?
                new ObjectParameter("Sexo", sexo) :
                new ObjectParameter("Sexo", typeof(string));
    
            var fecha_altaParameter = fecha_alta.HasValue ?
                new ObjectParameter("Fecha_alta", fecha_alta) :
                new ObjectParameter("Fecha_alta", typeof(System.DateTime));
    
            var idusuarioParameter = idusuario.HasValue ?
                new ObjectParameter("idusuario", idusuario) :
                new ObjectParameter("idusuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_NuevoUsuario", nombreParameter, apellidoParameter, sexoParameter, fecha_altaParameter, idusuarioParameter);
        }
    
        public virtual int sp_PrendaMasBarata(string descripcion, string modelo)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var modeloParameter = modelo != null ?
                new ObjectParameter("modelo", modelo) :
                new ObjectParameter("modelo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_PrendaMasBarata", descripcionParameter, modeloParameter);
        }
    }
}
