//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coconuts
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUBLICACIONES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PUBLICACIONES()
        {
            this.PRENDAS = new HashSet<PRENDAS>();
        }
    
        public int IDPUBLICACIONES { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<int> IDUSUARIO { get; set; }
        public string IMAGEN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRENDAS> PRENDAS { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
